# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
