# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-29 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise2', '0002_auto_20170428_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='time',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
